name: slack-notification

on:
  push

jobs:
  slack:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    
    steps:
      - uses: actions/checkout@v2
      - name: Notify Slack
        uses: act10ns/slack@v1
        env:
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
          SLACK_COLOR:  '#000080'
          SLACK_MESSAGE: 'Triggered By: ${{ github.actor }}'
          SLACK_TITLE: GitHub Action
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
