name: slack-notification

on:
  push

jobs:
  slack:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    
    steps:
      - uses: actions/checkout@v2
      - name: Notify Slack
        uses: act10ns/slack@v1
        with: 
          status: 'In progress'
          channel: ${{ secrets.SLACK_CHANNEL }}
          message: 'Triggered By: ${{ github.actor }}'
