name: slack-notification

on:
  push

jobs:
  slack:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Notify Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
          SLACK_COLOR:  '#000080'
          SLACK_MESSAGE: 'Triggered By: ${{ github.actor }}'
          SLACK_TITLE: GitHub Action
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          
  status-notification:
    runs-on: ubuntu-latest
    needs: slack
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.ref }}
        
      - name: Notify Deployed Status
        uses: rtCamp/action-slack-notify@v2
        
      - name: Exit Success
        if: ${{ success() }}
        env:
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE: 'Deploying ${{ github.event.client_payload.ref }} branch to ${{ github.event.client_payload.environment }} | Triggered By: ${{ github.actor }}'
          SLACK_TITLE: Successful
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        
      - name: Exit Failure
        if: ${{ failure() }}
        env:
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE: 'Deploying ${{ github.event.client_payload.ref }} branch to ${{ github.event.client_payload.environment }} | Triggered By: ${{ github.actor }}'
          SLACK_TITLE: Failure
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          
