name: slack-notification

on:
  push

jobs:
  slack:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Notify Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
          SLACK_COLOR:  '#000080'
          SLACK_MESSAGE: 'Deploy Triggered By: ${{ github.actor }}'
          SLACK_TITLE: Action
          SLACK_USERNAME: Project-IO
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_FOOTER: ' '
          
  sucess-notification:
    runs-on: ubuntu-latest
    needs: slack
    if: ${{ success() }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.ref }}
          
      - name: Notify Successful Status
        if: always()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
          SLACK_COLOR: 'good'
          SLACK_MESSAGE: 'Deploying ${{ github.event.client_payload.ref }} branch to ${{ github.event.client_payload.environment }} | Triggered By: ${{ github.actor }}'
          SLACK_TITLE: Successful
          SLACK_USERNAME: Project-IO GitHub Actions
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_FOOTER: Powered By GitHub Actions
          
  failure-notification:
    runs-on: ubuntu-latest
    needs: slack
    if: ${{ failure() }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.ref }}
          
      - name: Notify Successful Status
        if: always()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
          SLACK_COLOR: '#FF5733'
          SLACK_MESSAGE: 'Deploying ${{ github.event.client_payload.ref }} branch to ${{ github.event.client_payload.environment }} | Triggered By: ${{ github.actor }}'
          SLACK_TITLE: Failed
          SLACK_USERNAME: Project-IO
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_FOOTER: Powered By GitHub Actions
